### ISSUE TITLE
Canada overlay

### ISSUE THREAD

**Issue by jorrog** [signorprestito/ng-world-map-svg#1]
Hello is there a plat to include Canada in the countries options.

Best regards

**Comment by freefred81** [comment]
Hi ... sorry for the delay ... if you still wait for the mapping we'll do it in the week

**Comment by jorrog** [comment]
Hi, thanks, it will be great :)

**Comment by signorprestito** [comment]
Hi jorrog.

We've pushed the new release (```vs 1.0.10```) .. in it you can find the Canada svg map.

you can use it for example as following:

```
...
import { SvgMapModule, ICustomConfig} from "ng-world-map-svg";
...

@NgModule({
  imports: [
    ...
    SvgMapModule.forRoot(<ICustomConfig>{
      country : ["CAN"], //< -- HERE YOU CAN SET NOW CAN FOR CANADA
      googleAPIKey : "YOUR-API-KEY"
    })
  ],
  ...
  bootstrap: [AppComponent]
})
export class AppModule { }



```

Thnx for using our lib!!
